<a href="https://colab.research.google.com/github/saipatnaik-cse/DMDW-LAB-ASSIGNMENTS/blob/main/12_10_21_LAB_WORK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a)
b=np.array(([1,2],[3,4]))
print(b)
print(b.shape)

<class 'numpy.ndarray'>
[1 2 3]
[[1 2]
 [3 4]]
(2, 2)


In [ ]:
a=np.zeros((3,3))
print(a)
print(a.shape)
b=np.ones((4,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a=np.random.random((3,3))
print(a)

[[0.24023923 0.41920117 0.70945237]
 [0.37970546 0.37327964 0.18129754]
 [0.11930392 0.16703978 0.42326126]]


In [ ]:
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.arange(20)
print(a)
print(a[1:7:2]) #start , stop ,jump
print(a[5:15:3])
print(a[-1:5:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 3 5]
[ 5  8 11 14]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6]


In [ ]:
import numpy as np
a=np.array([[12,11],[9,7],[5,13]])
print(a.shape)
print(a>10)
print(b)
b=np.random.random((3,2))
print(a+b)
print(a-b)

(3, 2)
[[ True  True]
 [False False]
 [False  True]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[12.48348394 11.80184201]
 [ 9.11069526  7.53272289]
 [ 5.39517319 13.92987029]]
[[11.51651606 10.19815799]
 [ 8.88930474  6.46727711]
 [ 4.60482681 12.07012971]]


In [ ]:
import numpy as np
a=np.array([[12,11],[9,7],[5,13]])
print(a)
x=np.sum(a,axis=0)
print(x)

y=np.sum(a,axis=1)
print(y)

[[12 11]
 [ 9  7]
 [ 5 13]]
[26 31]
[23 16 18]


In [ ]:
a=np.array([[12,11],[9,7]])
print(a)
print()
print(a.T)

[[12 11]
 [ 9  7]]

[[12  9]
 [11  7]]


In [ ]:
import numpy as np
a=np.array([[12,11,15],[9,7,3]])
print(a)
print()
w=np.array([1.0,1.1,1.2])
print(w)
print(a+w)

[[12 11 15]
 [ 9  7  3]]

[1.  1.1 1.2]
[[13.  12.1 16.2]
 [10.   8.1  4.2]]


In [ ]:
a=np.array([[12,11,15],[9,7,3]])
w=np.array([1.0,1.1])
print((a.T+w).T)

[[13.  12.  16. ]
 [10.1  8.1  4.1]]


In [ ]:
import numpy as np
